const TOTAL_TILES = 16;
const TILES_PER_ROW = 4;
const EMPTY_TILE_VALUE = 0;
const MOVEMENT_DISTANCE = 1;
const FIRST_TILE_INDEX = 0;

export { TOTAL_TILES, TILES_PER_ROW, EMPTY_TILE_VALUE, MOVEMENT_DISTANCE, FIRST_TILE_INDEX };
