const SCREEN_ID_START = Symbol('SCREEN_ID_START');
const SCREEN_ID_PRACTICE = Symbol('SCREEN_ID_PRACTICE');
const SCREEN_ID_PLAY = Symbol('SCREEN_ID_PLAY');

export {
    SCREEN_ID_START,
    SCREEN_ID_PRACTICE,
    SCREEN_ID_PLAY
};
